### ISSUE TITLE
making tables with existing blocks is impossible now

### ISSUE THREAD

**Issue by Chuunkyz** [DaFuqs/Artis-Recrafted#1]
i added this in tables

_"minecraft:fletching_table": {
   "type": "existing_block",
   "width": 1,
    "height": 3
 }_

and the mod is trying to find artis:minecraft:fletching table

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'artis'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$gjj000$catchFabricInit(class_310.java:27478)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: artis:minecraft:fletching_table
	at net.minecraft.class_2960.<init>(class_2960.java:41)
	at net.minecraft.class_2960.<init>(class_2960.java:50)
	at io.github.alloffabric.artis.ArtisData.getType(ArtisData.java:81)
	at io.github.alloffabric.artis.ArtisData.loadEntries(ArtisData.java:61)
	at io.github.alloffabric.artis.ArtisData.loadConfig(ArtisData.java:44)
	at io.github.alloffabric.artis.Artis.onInitialize(Artis.java:89)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 13 more

**Comment by DaFuqs** [comment]
![image](https://user-images.githubusercontent.com/26429514/154476310-39d6c35f-be3d-4883-8c3a-d916f2be0da6.png)

Done for next version
